name: Docker

on:
  push:
    # branches: [ "main" ]
    tags: [ "v*.*.*" ]
  # schedule:
  #   - cron: "30 9 * * 5"
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: hub.docker.com
  # github.repository as <account>/<repo>
  IMAGE_NAME: scsys/proton
  IMAGE_TAG: latest


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerfile: Dockerfile
