name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: setup langspace
        run: rustup default ${{ matrix.toolchain }}
      - run: cargo build --workspace
      - run: cargo test --all --all-features -v
  
  publish:
    if: ${{ github.event.inputs.publish == true }}
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - tldr
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{matrix.package}})
        run: cargo publish --all-features -v -p ${{ matrix.package }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}